# Generated by Django 3.2.7 on 2021-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
