# Generated by Django 3.2.7 on 2021-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300),
        ),
    ]
