# Generated by Django 3.2.7 on 2021-09-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('file', models.FileField(upload_to='files', verbose_name='File')),
                ('file_type', models.CharField(choices=[('list', 'list'), ('slide', 'slide'), ('activity', 'activity')], max_length=15, verbose_name='File Type')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='book.unit')),
            ],
        ),
    ]
