# Generated by Django 3.2.7 on 2021-09-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210917_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='unit',
        ),
        migrations.AddField(
            model_name='resource',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='book.chapter'),
        ),
    ]
