# Generated by Django 3.2.7 on 2021-09-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210917_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='exam',
            field=models.FileField(blank=True, upload_to='exams', verbose_name='File'),
        ),
    ]
