# Generated by Django 3.2.7 on 2021-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_unit_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
    ]
