# Generated by Django 3.2.7 on 2021-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seo_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Seo Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
