# Generated by Django 3.2.7 on 2021-09-06 03:44

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.FileField(upload_to='book', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Cover')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='About')),
                ('organization', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Organization')),
            ],
        ),
    ]
