# Generated by Django 3.2.7 on 2021-09-07 00:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='about',
            field=ckeditor.fields.RichTextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='book',
            name='organization',
            field=ckeditor.fields.RichTextField(verbose_name='Organization'),
        ),
    ]
